bin/periphery/Dockerfile, bin/periphery/slim.Dockerfile
The original image was approximately 700 MB, which I believe can be significantly reduced. For comparison, the Portainer agent image is around 200 MB.
To achieve this reduction, I refactored the base image to use Alpine instead of Debian-slim, including only the necessary dependencies.
After that I got an image around 150 MB.
All functionality appears to remain consistent with the previous image.
I have do some tests : 
- Deploy and Remove a stack
- Build an image from a repository
- Prune system images
- Read some containers logs
- Prune volumes
=> Reduce periphery image size

scripts/setup-periphery.py
Adds a check at the beginning of setup-periphery.py to verify if `systemctl` is executable by the current user and if systemd is the init system in use. These changes will inform the user we've decided systemd is unavailable and exits before we attempt to use any systemd functionality, but modify this logic to configure other init systems in the future.
Relates to (but doesn't close) https://github.com/mbecker20/komodo/issues/66.
=> fix: check if systemd is available for install

docsite/docusaurus.config.ts
Changes the default edit url provided by the docusaurus template to the correct komodo url.
=> fix: change edit url for docsite

bin/periphery/src/docker.rs
Add or_else to allow attempt to connect to docker socket proxy via http if local connection fails, as per #87.
This was tested by adding env var DOCKER_HOST to the compose.env file (picked up by periphery container, which is run as a non-root user without the docker.sock volume defined), creating a new stack in Komodo (using redis image), then deploying. Deployment was successful, however the stack is marked as down in Komodo. I double-checked that the periphery agent is able to view running containers and the logs of those containers by exec-ing into the container and running the commands, so I am unsure where the issue lies.
=> Update docker.rs to allow http docker socket connection

frontend/src/components/topbar.tsx
Often when I'm in the UI I need to reference the docs but there is no quick way to access them. This PR adds a [Docs](https://komo.do/docs/intro) link in the topbar next to the Version. 
It follows the same media breakpoints as version so it's out of the way on smaller screen sizes.
=> feat: Add docs link to topbar

.devcontainer/dev.compose.yaml, .devcontainer/devcontainer.json, .devcontainer/postCreate.sh, .vscode/extensions.json, .vscode/tasks.json, docsite/docs/development.md, docsite/sidebars.ts, expose.compose.yaml, runfile.toml
This is a WIP for a jumping off point for users trying to develop or contribute to Komodo. The doc I've added is missing a few things and I had a few questions about dependencies and modifying test files:
On my machine (Arch kernel 6.10.9) Trying to run `cargo build` with Rust 1.81 (stable) I get a build error:
```
error: package `aws-sdk-sso v1.45.0` cannot be built because it requires rustc 1.78.0 or newer, while the currently active rustc version is 1.75.0
Either upgrade to rustc 1.78.0 or newer, or use
cargo update aws-sdk-sso@1.45.0 --precise ver
where `ver` is the latest version of `aws-sdk-sso` supporting rustc 1.75.0
```
Are you developing with nightly/unstable Rust? I did not see anything specific in the repo about what Rust version is required.
There is no port exposed in …
=> docs: Add development docs

bin/core/src/api/execute/stack.rs, bin/periphery/src/compose.rs, client/core/rs/src/entities/stack.rs, client/core/ts/src/types.ts, frontend/public/client/types.d.ts, frontend/src/components/resources/stack/config.tsx
This PR adds a post_deploy command, similar to the pre_deploy.
i needed to test a use-case for this, the issue that gave me the idea is here : https://github.com/moghtech/komodo/issues/227
ℹ️ what is unclear to me is the expected/wanted behaviour in case of the post_deploy fails (we could say the deployment was ok since compose up ran fine, but we can also fail the whole action)
=> feature: add post_deploy command

bin/core/src/alert/mod.rs
This is something i really need, in order to be able to manage my alerters with a git sync without exposing my secrets.
I have a custom endpoint to which i add a secret token, not perfect security-wise (headers would be better) but i think it can still be an improvement for some users.
⚠️ i didn't attempt to sanitise the trace, that could be beyond my knowledge of rust and this awesome project ^^
=> feature: interpolate secrets in custom alerter

frontend/src/pages/resources.tsx
Another small but annoying thing on mobile :) 
The quick actions above the table are not responsive, causing the whole page to be "wider" that the screen, not sure how to describe it but the page sort of floats all around:
With this change, on small screens the actions are stacked, so the page is on the correct screen size: 
With wide screens:
=> feature: improve tables quick actions on mobile

scripts/setup-periphery.py
'arm64' was mistyped as 'amd64', meaning if amd64 was the architecture, it would install the aarch64 binary rather than the x86_64 one. This PR fixes that.
=> Fix: amd64 architecture could trigger installation of aarch64 binary

bin/periphery/src/docker.rs
Just found a bug about the docker login process.
I tried Harbor as my image storage, their username always generate in the format of: `robot$something+username`.
I found that I could not set robot$something+username in the Registry Accounts Setting. 
It will lead to 
`Error response from daemon: Get "https://XXX/v2/": unauthorized`
After some research, docker login for this kind of username needs to be 
`docker login XXX --username 'robot$something+username'` instead of `docker login XXX --username robot$something+username`  stated in the code (username needs to be single quoted, found that the code are not quoted)
Not sure if normal username will be affected also
Tested in command line, single quoting a normal username on ghcr.io logins fine
=> Fix: The {account} login fails when the name contains '$' sign

bin/core/src/api/read/mod.rs, bin/core/src/api/read/server.rs, client/core/rs/src/api/read/server.rs, client/core/ts/src/responses.ts, client/core/ts/src/types.ts, frontend/public/client/responses.d.ts, frontend/public/client/types.d.ts
I wanted to create a custom homepage widget for Komodo so I could just see what was running/stopped and a total count but an endpoint like `GetDeploymentsSummary` and `GetStacksSummary` didn't exist for all containers. 
At first, I just made a separate python API (https://github.com/alexshore/komodo-containers-api) but thought this could be a good way to up my contributions to open source software so heres my attempt at contributing a `GetDockerContainersSummary` endpoint :)
I'm not too fussed as what counts as what category. For my use-case it's helpful for there really to just be 2 final "states" that the docker containers are categorised into (i.e. just Stopped and Running) but thats a bit more specific to my use-case than to Komodo so right now they're split into Stopped, Running, …
=> Adding a read API endpoint to get container states similar to GetDeploymentsSummary but for all containers that Komodo can see.

bin/core/src/alert/mod.rs, bin/core/src/alert/ntfy.rs, client/core/rs/src/entities/alerter.rs, client/core/ts/src/types.ts, frontend/public/client/types.d.ts, frontend/src/components/resources/alerter/config/endpoint.tsx
Adds [ntfy](https://github.com/binwiederhier/ntfy) as an Alerter
before with custom alerter / after
=> Ntfy as Alerter

compose/periphery.compose.yaml, docsite/docs/connect-servers.mdx
Hello, I want to start by thanking you for all the work you have put in to komodo. I just found it a couple weeks ago and have been migrating my systems to it. I have been using systemd to run periphery per the recommendations that you and FoxxMD have made, but I don't think that is practical for the last couple of systems, so I had to dig into running periphery in a container and ran into a couple things that weren't clear to me and required some guess and check, so I'm submitting this PR to hopefully eliminate that uncertainty for people in the future.
Happy to take any feedback and make changes as you see fit.
=> Improve docs around running periphery in a container

bin/core/src/config.rs, bin/core/src/main.rs, bin/periphery/src/config.rs, bin/periphery/src/main.rs, client/core/rs/src/entities/config/core.rs, client/core/rs/src/entities/config/periphery.rs, config/core.config.toml, config/periphery.config.toml
This PR makes the listener address configurable for both Core and Periphery through the following env vars:
`CORE_LISTENER_ADDRESS`
`PERIPHERY_LISTENER_ADDRESS`
But the main purpose of this PR is to add support for IPv6.
Before:
```
ss -tulpn | grep 120
tcp   LISTEN 0      1024              0.0.0.0:9120       0.0.0.0:*    users:(("core",pid=4694,fd=13))          
tcp   LISTEN 0      1024              0.0.0.0:8120       0.0.0.0:*    users:(("periphery",pid=4702,fd=10))
```
After:
```
ss -tulpn | grep 120
tcp   LISTEN 0      1024                      *:8120             *:*    users:(("periphery",pid=163028,fd=9))    
tcp   LISTEN 0      1024                      *:9120             *:*    users:(("core",pid=163036,fd=15))
```
Fixes https://github.com/moghtech/komodo/issues/313
=> Make listener address configurable & Add support for IPv6

docsite/docs/resources.md
Removing ServerTemplate from Resources documentation, as it was removed in Release v1.17.5
=> Removing ServerTemplate in docs

bin/core/src/alert/mod.rs, bin/core/src/alert/ntfy.rs, client/core/rs/src/entities/alerter.rs, client/core/ts/src/types.ts, frontend/public/client/types.d.ts, frontend/src/components/resources/alerter/config/endpoint.tsx
Originally I only wanted a way to receive email notifications from komodo alerts, and found out that ntfy allows forwarding notifications via email by adding a "X-Email" header to a notification request. So I implemented that, and while I was at it, I also added support for customizing the notification title and message priority:
- in the frontend when setting the alerter type to "ntfy", new configuration fields will pop up
- the default notification title was change from "ntfy alert" to "Komodo Alert", and can be customized if desired
- the main use-case for message priorities is for usage with the ntfy android app, which will notify the user more (or less) urgently (see [the ntfy documentation](https://docs.ntfy.sh/publish/#message-priority))
For the future, maybe it would be nice to …
=> Ntfy alerter: Add support for email notifications, notification titles and message priorities

docsite/docs/setup/advanced.mdx
[Keycloak](https://www.keycloak.org/) is a self hosted open source identity and access management solution. I've added instructions to the Advanced Configuration page on how to set it up as OIDC provider.
=> Add Keycloak instructions to OIDC setup

Cargo.toml, bin/periphery/Cargo.toml, bin/periphery/src/api/router.rs, client/core/rs/Cargo.toml, client/core/rs/src/entities/config/periphery.rs
Attempt to implement #631 
Changes `allowed_ips` from `IpAddr` to `IpNetwork`. The default serde will accept IP addresses and convert them to a /32 or /128 prefix if needed (depending on if the IP is v4 or v6).
For example
```yaml
periphery:
environment:
PERIPHERY_ALLOWED_IPS: "172.25.3.0/24,172.25.0.4,::ffff:172.25.55.3/64,::ffff:172.25.55.4"
```
Turns into
```
allowed_ips: [V4(Ipv4Network { addr: 172.25.3.0, prefix: 24 }), V4(Ipv4Network { addr: 172.25.0.4, prefix: 32 }), V6(Ipv6Network { addr: ::ffff:172.25.55.3, prefix: 64 }), V6(Ipv6Network { addr: ::ffff:172.25.55.4, prefix: 128 })]
```
I also added a check to the matching function in `guard_request_by_ip` that will check the ip network type, and when the network is IPv4, it will convert the address to its canonical form. This way, …
=> Allow CIDR ranges in Allowed IPs

bin/core/src/auth/oidc/mod.rs
Komodo is making a request to the oidc discoverable endpoint every 60s.
currently the user agent is empty, making investigations into request utilization difficult. 
this adds a Komodo specific user agent to allow others to easily discover when Komodo is making requests to their other services.
fixes: #660
=> add user agent to oidc requests

bin/periphery/src/docker/stats.rs
By default podman stats uses different fields than docker. With this change it will use the docker formatted stats and fixes the stats display in komodo for podman hosts.
=> Fix podman compatibility in `get_container_stats`

frontend/src/components/resources/server/index.tsx, frontend/src/components/resources/server/stats-mini.tsx, frontend/src/lib/dashboard-preferences.ts, frontend/src/pages/home/dashboard.tsx
Currently, there’s no quick way to view all servers’ resource usage (CPU, memory, disk) in the dashboard. Users must click into each server to see these stats, which slows down monitoring.
https://github.com/moghtech/komodo/issues/46
=> feat(dashboard): display CPU, memory, and disk usage on server cards

docsite/docs/resources/permissioning.md
=> Update permissioning.md - typo: "priviledges" -> "privileges"

frontend/package.json, frontend/public/schema/compose-spec.json, frontend/src/components/monaco.tsx, frontend/src/components/resources/stack/config.tsx, frontend/src/components/resources/stack/info.tsx, frontend/src/monaco/index.ts, frontend/src/monaco/yaml.ts, frontend/yarn.lock
Spawned out of a [discussion from Discord](https://discord.com/channels/1272479750065094760/1283197688292048949/1408907915125063700) this PR adds support for the [monaco-yaml](https://github.com/remcohaszing/monaco-yaml) package, which allows reading a JSON Schema offering type-hints for Docker Compose files 
1. Have a Komodo Core environment which has different kinds of compose files (files on disk, UI defined, etc) along with arbitrary yaml files defined as sidecar configs 
2. Navigate between different kinds of editors
3. Only docker compose file yaml files should have type hints from the plugin, others should be ignored. 
4. There should be no regressions with the rest of the editors
=> Add support for monaco-yaml and docker compose spec validatiaon

frontend/src/components/util.tsx, frontend/src/pages/login.tsx, frontend/src/router.tsx
Solves https://github.com/moghtech/komodo/issues/403 
and maybe https://github.com/moghtech/komodo/issues/652 but I couldn't reproduce _everything_ from that issue so unsure. I tested with iOS, safari and bitwarden, protonpass
this PR improves the login page form implementation. Main changes are replacing local state for credentials with native form submission and improving accessability. I also looked at https://www.chromium.org/developers/design-documents/create-amazing-password-forms/ for some tips.
also removed the unused `WithLoading` component from `util.tsx` (i couldnt find any other references of it)
=> Improve login form

frontend/src/components/layouts.tsx
Resolves #771
When creating a new resource with a duplicate name, the API call fails but the submit button becomes permanently disabled. Even after updating the input field with a valid name, the button stays disabled because the dialog was closing on error, preventing proper state re-evaluation.
The original code called `set(false)` and `setLoading(false)` regardless of success/failure, causing the component to unmount before the `enabled={!!name}` prop could be re-evaluated.
Added proper error handling in `NewLayout` component:
- Wrapped `onConfirm()` in try-catch block
- Only close dialog on successful API calls
- Keep dialog open on errors so users can retry
- Always reset loading state in `finally` block
This fix applies to all resource creation flows that use the `NewResource` …
=> Fix: Submit button remains disabled after failed API calls

frontend/src/components/group-actions.tsx
When selecting all stacks (40+) in group actions, the confirmation dialog becomes too tall and the bottom buttons are inaccessible, requiring users to zoom out their browser to reach the confirm/cancel buttons.
- Added `max-h-[85vh]` to dialog container to prevent overflow beyond viewport height
- Added `max-h-[300px] overflow-y-auto` to resource list for scrollable content
- Dialog footer remains always accessible regardless of selection count
Fixes #826
=> Fix confirmation dialog height overflow when selecting many stacks

frontend/src/ui/data-table.tsx
Stack sorting preferences do not persist across page reloads. When a user sorts stacks alphabetically or reverse-alphabetically and then switches back to unsorted and navigates away or reloads the page, the sorting is lost. More specifically, when the table is in "unsorted" state (showing "-" in column header), it incorrectly reverts to the previous sorted state (e.g., reverse-alphabetical) after page reload.
- Removed conditional check in localStorage saving logic to always persist sorting state
- Now saves empty sorting array (`[]`) for "unsorted" state instead of skipping it
- Ensures all table sorting states are consistently preserved across page reloads
- Applies to all DataTable components throughout the application
Fixes #816
=> Fix persistent table sorting state including unsorted

frontend/src/components/resources/server/index.tsx, frontend/src/components/resources/server/monitoring-table.tsx, frontend/src/components/resources/server/stats.tsx
While working on server management, I noticed that the frontend was making tons of unnecessary API calls to servers that have a "Not OK" status. Every time you visit a server page with an unreachable server, the UI tries to fetch system stats, CPU info, memory data, and container information - all of which are guaranteed to fail with 500 errors, flooding the browser console.
This creates several issues:
- Browser console spam with repeated 500 errors from `GetSystemStats` and `GetSystemInformation`
- Pointless backend load from requests that will never succeed
- Poor user experience with constant failed API calls
- Network traffic waste for unreachable servers
I've added server availability guards to prevent API calls to unreachable servers:
1. **New Helper Function**: …
=> Fix unnecessary API queries to unreachable servers flooding console
